name: CICD
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./server
        run: npm install
      - name: Generate deployment package zip
        working-directory: ./server
        run: zip -r ecommerce-sample-app-build.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.ACCESS_KEY }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: 'backend-project-1'
          environment_name: 'Backend-project-1-env'
          version_label: ${{ github.sha }}
          region: eu-north-1
          deployment_package: ecommerce-sample-app-build.zip
